---
internal_url: !secret internal_url
external_url: !secret external_url
latitude: !secret latitude_home
longitude: !secret longitude_home
elevation: 0
unit_system: metric
time_zone: Europe/Amsterdam
name: !secret hass_name
customize: !include ../../customize.yaml
auth_providers:
  - type: homeassistant
