- id: '1579814218996'
  alias: Bright
  description: ''
  trigger:
  - entity_id: sensor.cube_living_room
    platform: state
    to: rotate_right
  condition: []
  action:
  - data: {}
    service: script.brightness_up
- id: '1579814442696'
  alias: down
  description: ''
  trigger:
  - entity_id: sensor.cube_living_room
    platform: state
    to: rotate_left
  condition: []
  action:
  - service: script.brightness_down
