background: var(--background-image)
custom_header:
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
  compact_mode: true
  menu_hide: true
resources:
- type: module
  url: /community_plugin/custom-header/custom-header.js
- type: module
  url: /community_plugin/mini-media-player/mini-media-player-bundle.js
- type: module
  url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
state-icon-active-color: '#0F0'
title: Home Assistant
views:
- badges:
  - entity: person.rein_van_haaren
  - entity: person.bas_menting
  - entity: input_boolean.guest_mode
  - entity: sun.sun
  cards:
  - entities:
    - entity: scene.living_room_evening
    - entity: scene.living_room_shawarma
    - entity: scene.room_rein_evening
    - entity: scene.room_rein_bright
    show_header_toggle: false
    title: Scenes
    type: entities
  - entity: weather.buienradar
    name: Buienradar
    type: weather-forecast
  - aspect_ratio: 0%
    camera_image: camera.buienradar
    entities: []
    image: https://www.home-assistant.io/images/merchandise/shirt-frontpage.png
    title: Buienradar
    type: picture-glance
  icon: mdi:home
  path: general
  title: General
- badges: []
  cards:
  - entities:
    - entity: input_boolean.guest_mode
    show_header_toggle: false
    title: General
    type: entities
  - entities:
    - entity: light.living_room
      full_row: true
      hide_state: true
      min: 1
      step: 1
      type: custom:slider-entity-row
    - entity: light.couch
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.living_room_ridge
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.living_room_turtle_chair
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.tv
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.corner
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.kitchen
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.christmas_tree
    show_header_toggle: true
    title: Living Room
    type: entities
  - entities:
    - entity: light.rein_ceiling
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.room_rein_bed
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    title: Room Rein
    type: entities
  - entities:
    - entity: light.room_bas
      full_row: true
      hide_state: true
      min: 1
      step: 1
      type: custom:slider-entity-row
    - entity: light.bas_ceiling
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.room_bas_bed
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    title: Room Bas
    type: entities
  - entities:
    - entity: light.hallway
      hide_state: true
      max: 100
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: binary_sensor.door_living_room
    show_header_toggle: false
    title: Hallway
    type: entities
  - entities:
    - entity: binary_sensor.washing_machine
    - entity: sensor.washing_machine_usage
    show_header_toggle: false
    title: Bathroom
    type: entities
  icon: mdi:lightbulb
  path: light
  theme: ios-dark-mode
  title: Light
- badges: []
  cards:
  - entity: climate.heating
    theme: ios-dark-mode
    type: thermostat
  - entities:
    - entity: switch.button_ventilation_off
      hold_action:
        action: more-info
      name: 'Off'
      show_icon: true
      show_name: true
      tap_action:
        action: toggle
      type: entity-button
    - entity: switch.button_ventilation_medium
      hold_action:
        action: more-info
      name: Medium
      show_icon: true
      show_name: true
      tap_action:
        action: toggle
      type: entity-button
    - entity: switch.button_ventilation_high
      hold_action:
        action: more-info
      name: High
      show_icon: true
      show_name: true
      tap_action:
        action: toggle
      type: entity-button
    show_icon: true
    show_name: true
    show_state: false
    title: Ventilation
    type: glance
  icon: mdi:coolant-temperature
  path: temp
  title: Temp
- badges: []
  cards:
  - entities:
    - entity: binary_sensor.washing_machine
    - entity: sensor.washing_machine_usage
    show_header_toggle: false
    title: Washing machine
    type: entities
  - entities:
    - entity: input_boolean.enable_washing_machine_schedule
      name: Autostart on
    - entity: input_datetime.end_time_washing_machine
      name: Set end time
    - entity: sensor.start_time_washing_machine
    - entity: sensor.end_time_washing_machine
    show_header_toggle: false
    title: Schedule
    type: entities
  icon: mdi:washing-machine
  path: washing-machine
  title: Washing machine
- badges: []
  cards:
  - cards:
    - entity: media_player.chromecast
      type: custom:mini-media-player
    - entity: media_player.tv
      type: custom:mini-media-player
    - entity: media_player.google_home
      type: custom:mini-media-player
    - entity: media_player.spotify_rein_van_haaren
      type: custom:mini-media-player
    type: vertical-stack
  icon: mdi:monitor-speaker
  path: media-players
  title: Media Players
- badges: []
  cards:
  - entities:
    - entity: sensor.button_living_room_wall_battery
    - entity: sensor.button_hallway_front_battery
    - entity: sensor.button_room_rein_wall_battery
    - entity: sensor.button_room_rein_bed_battery
    - entity: sensor.button_room_bas_wall_battery
    show_header_toggle: false
    title: Buttons
    type: entities
  - entities:
    - entity: sensor.door_living_room_battery
    - entity: sensor.cube_living_room_battery
    show_header_toggle: false
    title: Other
    type: entities
  icon: mdi:battery-alert
  path: battery-status
  title: Battery status
- badges: []
  cards:
  - entities:
    - entity: binary_sensor.tv_source_youtube
    - entity: binary_sensor.tv_source_spotify
    - entity: binary_sensor.tv_source_netflix
    - entity: binary_sensor.tv_source_tunein
    - entity: binary_sensor.tv_source_off
    show_header_toggle: false
    title: TV Lamp
    type: entities
  - entities:
    - entity: switch.ventilation_medium
    - entity: switch.ventilation_high
    title: Relays
    type: entities
  icon: mdi:test-tube
  path: test
  title: Test
