custom_header:
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
  compact_mode: true
  menu_hide: true
resources:
- type: module
  url: /community_plugin/custom-header/custom-header.js
- type: module
  url: /community_plugin/mini-media-player/mini-media-player-bundle.js
- type: module
  url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
- type: module
  url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
- type: js
  url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
- type: module
  url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
- type: module
  url: /community_plugin/button-card/button-card.js
- tpye: module
  url: /community_plugin/weather-card/weather-card.js
state-icon-active-color: '#0F0'
title: Home Assistant
views:
- badges:
  - entity: person.rein_van_haaren
  - entity: person.bas_menting
  cards:
  - cards:
    - entities:
      - entities:
        - entity: light.couch
          hide_state: true
          min: 1
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.living_room_ridge
          hide_state: true
          min: 1
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.living_room_turtle_chair
          hide_state: true
          min: 1
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.corner
          hide_state: true
          min: 1
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.living_room_tv
          hide_state: true
          min: 1
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.christmas_tree
        head:
          entity: light.living_room
          icon: mdi:sofa
          min: 0
          step: 1
          type: custom:slider-entity-row
        type: custom:fold-entity-row
      - entities:
        - entity: light.kitchen_cabinets_map
          hide_state: true
          min: 1
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.kitchen_extractor_hood
          hide_state: true
          min: 1
          step: 1
          toggle: true
          type: custom:slider-entity-row
        head:
          entity: light.kitchen
          icon: mdi:stove
          min: 0
          step: 1
          type: custom:slider-entity-row
        type: custom:fold-entity-row
      - entities:
        - entity: light.hallway_1
          hide_state: true
          min: 1
          name: Hallway Front 1
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.hallway_2
          hide_state: true
          min: 1
          name: Hallway Front 2
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.hallway_3
          hide_state: true
          min: 1
          name: Hallway Back 1
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.hallway_4
          hide_state: true
          min: 1
          name: Hallway Back 2
          step: 1
          toggle: true
          type: custom:slider-entity-row
        head:
          entity: light.hallway
          icon: mdi:door-closed
          min: 0
          step: 1
          type: custom:slider-entity-row
        type: custom:fold-entity-row
      - entities:
        - entity: light.room_rein_1
          hide_state: true
          min: 1
          name: Ceiling Left
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.room_rein_2
          hide_state: true
          min: 1
          name: Ceiling Right
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.room_rein_bed
          hide_state: true
          min: 1
          name: Bed
          step: 1
          toggle: true
          type: custom:slider-entity-row
        head:
          entity: light.room_rein
          icon: mdi:bed-empty
          min: 0
          step: 1
          type: custom:slider-entity-row
        type: custom:fold-entity-row
      - entities:
        - entity: light.room_bas_ceiling_1
          hide_state: true
          min: 1
          name: Ceiling Left
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.room_bas_ceiling_2
          hide_state: true
          min: 1
          name: Ceiling Right
          step: 1
          toggle: true
          type: custom:slider-entity-row
        - entity: light.room_bas_bed
          hide_state: true
          min: 1
          name: Bed
          step: 1
          toggle: true
          type: custom:slider-entity-row
        head:
          entity: light.room_bas
          icon: mdi:bed-empty
          min: 0
          step: 1
          type: custom:slider-entity-row
        type: custom:fold-entity-row
      - entity: light.storage_room
      show_header_toggle: false
      title: Lights
      type: entities
    - cards:
      - color: auto
        entity: input_boolean.guest_mode
        icon: "[[[\n  if (entity.state !== 'on')\n    return 'mdi:bag-carry-on-off';\n\
          \  else {\n    return 'mdi:bag-checked';\n  }\n]]]\n"
        name: "[[[\n  if (entity.state !== 'on')\n    return 'Activate Guest Mode';\n\
          \  else {\n    return `Guest Mode active`\n  }\n]]]\n"
        styles:
          card:
          - font-size: 12px
          - font-weight: bold
          - height: 70px
        type: custom:button-card
      - color: auto
        entity: input_boolean.dummy
        icon: mdi:account-clock
        name: Reset Guest Mode timer
        styles:
          card:
          - font-size: 12px
          - font-weight: bold
          - height: 70px
        tap_action:
          action: call-service
          haptic: success
          service: script.reset_guest_mode_timer
        type: custom:button-card
      type: horizontal-stack
    - entities:
      - entity: input_datetime.guest_mode_active_until
      type: entities
    - entity: weather.buienradar
      name: Buienradar
      type: weather-forecast
    type: vertical-stack
  - cards:
    - background: /local/images/card_background_tv.png
      entity: media_player.tv
      hide:
        controls: true
        power: false
        source: false
        volume: true
      type: custom:mini-media-player
    - background: /local/images/card_background_chromecast.png
      entity: media_player.chromecast
      hide:
        power: false
        source: false
        volume: true
      icon: mdi:spotify
      type: custom:mini-media-player
    - artwork: cover
      entity: media_player.spotify_rein_van_haaren
      hide:
        power: true
        source: false
        volume: true
      icon: mdi:spotify
      type: custom:mini-media-player
    - entities:
      - entity: binary_sensor.washing_machine
        name: State
      - entity: sensor.washing_machine_usage
        name: Usage
      - entity: timer.washing_machine_remaining
        icon: mdi:clock-check
        name: Estimated time remaining
      show_header_toggle: false
      title: Washing machine
      type: entities
    type: vertical-stack
  - cards:
    - entity: climate.heating
      type: thermostat
    - cards:
      - entities:
        - entity: sensor.environment_living_room_temperature
          index: 0
        font_size: 80
        group: false
        hour24: true
        line_width: 2
        points_per_hour: 1
        show:
          extrema: false
          fill: fade
          labels: true
          name: true
          state: true
        type: custom:mini-graph-card
      - entities:
        - entity: sensor.environment_bathroom_temperature
          index: 0
        font_size: 80
        group: false
        hour24: true
        line_width: 2
        points_per_hour: 1
        show:
          extrema: false
          fill: fade
          labels: true
          name: true
          state: true
        type: custom:mini-graph-card
      - entities:
        - entity: sensor.temperature_room_rein
          index: 0
        font_size: 80
        group: false
        hour24: true
        line_width: 2
        points_per_hour: 1
        show:
          extrema: false
          fill: fade
          labels: true
          name: true
          state: true
        type: custom:mini-graph-card
      type: custom:vertical-stack-in-card
    type: vertical-stack
  icon: mdi:home
  path: general
  title: General
- badges: []
  cards:
  - entities:
    - entity: input_boolean.guest_mode
    - entity: input_datetime.guest_mode_active_until
    show_header_toggle: false
    title: General
    type: entities
  - entities:
    - entity: light.living_room
      full_row: true
      hide_state: true
      min: 1
      step: 1
      type: custom:slider-entity-row
    - entity: light.couch
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.living_room_ridge
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.living_room_turtle_chair
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.tv
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.corner
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.kitchen_cabinets_map
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.christmas_tree
    show_header_toggle: true
    title: Living Room
    type: entities
  - entities:
    - entity: light.room_rein
      full_row: true
      hide_state: true
      min: 1
      step: 1
      type: custom:slider-entity-row
    - entity: light.rein_ceiling
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.room_rein_bed
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    title: Room Rein
    type: entities
  - entities:
    - entity: light.room_bas
      full_row: true
      hide_state: true
      min: 1
      step: 1
      type: custom:slider-entity-row
    - entity: light.bas_ceiling
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: light.room_bas_bed
      hide_state: true
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    title: Room Bas
    type: entities
  - entities:
    - entity: binary_sensor.washing_machine
    - entity: sensor.washing_machine_usage
    show_header_toggle: false
    title: Bathroom
    type: entities
  - entities:
    - entity: light.hallway
      hide_state: true
      max: 100
      min: 1
      step: 1
      toggle: true
      type: custom:slider-entity-row
    - entity: binary_sensor.door_living_room
    - entity: binary_sensor.motion_hallway_front
      icon: mdi:motion-sensor
      name: Motion Hallway Front
    - entity: binary_sensor.motion_hallway_back
      icon: mdi:motion-sensor
      name: Motion Hallway Back
    show_header_toggle: false
    title: Hallway
    type: entities
  icon: mdi:lightbulb
  path: light
  theme: ios-dark-mode
  title: Light
- badges: []
  cards:
  - entity: climate.heating
    theme: ios-dark-mode
    type: thermostat
  - entities:
    - entity: switch.button_ventilation_off
      hold_action:
        action: more-info
      name: 'Off'
      show_icon: true
      show_name: true
      tap_action:
        action: toggle
      type: entity-button
    - entity: switch.button_ventilation_medium
      hold_action:
        action: more-info
      name: Medium
      show_icon: true
      show_name: true
      tap_action:
        action: toggle
      type: entity-button
    - entity: switch.button_ventilation_high
      hold_action:
        action: more-info
      name: High
      show_icon: true
      show_name: true
      tap_action:
        action: toggle
      type: entity-button
    show_icon: true
    show_name: true
    show_state: false
    title: Ventilation
    type: glance
  - entities:
    - entity: sensor.environment_living_room_temperature
    - entity: sensor.temperature_room_rein
    type: entities
  icon: mdi:coolant-temperature
  path: temp
  title: Temp
- badges: []
  cards:
  - entities:
    - entity: binary_sensor.washing_machine
    - entity: sensor.washing_machine_usage
    show_header_toggle: false
    title: Washing machine
    type: entities
  - entities:
    - entity: input_boolean.enable_washing_machine_schedule
      name: Autostart on
    - entity: input_datetime.end_time_washing_machine
      name: Set end time
    - entity: sensor.start_time_washing_machine
    - entity: sensor.end_time_washing_machine
    show_header_toggle: false
    title: Schedule
    type: entities
  icon: mdi:washing-machine
  path: washing-machine
  title: Washing machine
- badges: []
  cards:
  - cards:
    - entity: media_player.spotify_rein_van_haaren
      type: custom:mini-media-player
    - entity: media_player.google_home
      type: custom:mini-media-player
    title: Audio
    type: vertical-stack
  - cards:
    - entity: media_player.chromecast
      type: custom:mini-media-player
    - entity: media_player.tv
      type: custom:mini-media-player
    - entity: media_player.plex_lg_43uj670v_zd
      type: custom:mini-media-player
    - entity: media_player.playstation_4
      type: custom:mini-media-player
    title: Video
    type: vertical-stack
  icon: mdi:monitor-speaker
  path: media-players
  title: Media Players
- badges: []
  cards:
  - entities:
    - entity: sensor.button_living_room_wall_battery
    - entity: sensor.button_hallway_front_battery
    - entity: sensor.button_room_rein_wall_battery
    - entity: sensor.button_room_rein_bed_battery
    - entity: sensor.button_room_bas_wall_battery
    show_header_toggle: false
    title: Buttons
    type: entities
  - entities:
    - entity: sensor.door_living_room_battery
    - entity: sensor.cube_living_room_battery
    - entity: sensor.motion_hallway_back_battery
    show_header_toggle: false
    title: Other
    type: entities
  icon: mdi:battery-alert
  path: battery-status
  title: Battery status
- badges: []
  cards:
  - entities:
    - entity: binary_sensor.tv_source_youtube
    - entity: binary_sensor.tv_source_spotify
    - entity: binary_sensor.tv_source_netflix
    - entity: binary_sensor.tv_source_tunein
    - entity: binary_sensor.tv_source_off
    show_header_toggle: false
    title: TV Lamp
    type: entities
  - entities:
    - entity: switch.heater
    - entity: switch.ventilation_medium
    - entity: switch.ventilation_high
    title: Relays
    type: entities
  - entities:
    - entity: binary_sensor.motion_hallway_front
    - entity: binary_sensor.motion_hallway_back
    - entity: binary_sensor.motion_hallway
    - entity: timer.light_hallway
    - entity: timer.light_storage_room
    - entity: sensor.light_intensity_hallway
    show_header_toggle: false
    title: Motion
    type: entities
  - entities:
    - entity: binary_sensor.nobody_home
    - entity: light.kitchen_extractor_hood
    - entity: light.living_room_tv
    - entity: light.storage_room
    - entity: input_boolean.test_boolean
    - entity: binary_sensor.sleep_mode
    show_header_toggle: false
    title: Overig
    type: entities
  - cards:
    - entities:
      - entity: sensor.light_intensity_hallway
        index: 0
      font_size: 80
      group: false
      hour24: true
      line_width: 2
      points_per_hour: 1
      show:
        extrema: false
        fill: fade
        labels: true
        name: true
        state: true
      type: custom:mini-graph-card
    - entities:
      - entity: sensor.environment_bathroom_humidity
        index: 0
      font_size: 80
      group: false
      hour24: true
      line_width: 2
      points_per_hour: 5
      show:
        extrema: false
        fill: fade
        labels: true
        name: true
        state: true
      type: custom:mini-graph-card
    type: vertical-stack
  - entities:
    - entity: binary_sensor.ventilation_shower
    - entity: binary_sensor.ventilation_cooking
    - entity: binary_sensor.ventilation_high
    - entity: binary_sensor.ventilation_medium
    - entity: binary_sensor.ventilation_off
    show_header_toggle: false
    title: Ventilation
    type: entities
  icon: mdi:test-tube
  path: test
  title: Test
