- id: '1579726678052'
  name: Living Room Evening
  entities:
    light.kitchen_cabinets:
      brightness: 1
      friendly_name: Kitchen
      state: 'on'
      supported_features: 41
    light.living_room_corner:
      brightness: 36
      color_temp: 303
      friendly_name: Corner
      max_mireds: 1000
      min_mireds: 100
      state: 'on'
      supported_features: 3
    light.living_room_couch_1:
      brightness: 1
      friendly_name: Couch 1
      state: 'on'
      supported_features: 41
    light.living_room_couch_2:
      brightness: 1
      friendly_name: Couch 2
      state: 'on'
      supported_features: 41
    light.living_room_couch_3:
      brightness: 1
      friendly_name: Couch 3
      state: 'on'
      supported_features: 41
    light.living_room_ridge:
      brightness: 1
      color_temp: 444
      friendly_name: Ridge
      max_mireds: 500
      min_mireds: 153
      state: 'on'
      supported_features: 43
    light.living_room_turtle_chair:
      brightness: 1
      color_temp: 451
      friendly_name: Turtle chair
      max_mireds: 500
      min_mireds: 153
      state: 'on'
      supported_features: 43
    light.living_room_tv:
      brightness: 127
      color:
        x: 0.217
        y: 0.077
      friendly_name: TV
      hs_color:
      - 270.824
      - 100
      rgb_color:
      - 131
      - 0
      - 255
      state: 'on'
      supported_features: 57
      update_available: true
      xy_color:
      - 0.222
      - 0.079
- id: '1579726887557'
  name: Living Room Shawarma
  entities:
    light.kitchen_cabinets:
      brightness: 235
      friendly_name: Kitchen
      state: 'on'
      supported_features: 41
    light.living_room_corner:
      brightness: 250
      color_temp: 100
      friendly_name: Corner
      max_mireds: 1000
      min_mireds: 100
      state: 'on'
      supported_features: 3
    light.living_room_couch_1:
      brightness: 255
      friendly_name: Couch 1
      state: 'on'
      supported_features: 41
    light.living_room_couch_2:
      brightness: 255
      friendly_name: Couch 2
      state: 'on'
      supported_features: 41
    light.living_room_couch_3:
      brightness: 1
      friendly_name: Couch 3
      state: 'on'
      supported_features: 41
    light.living_room_ridge:
      brightness: 255
      color_temp: 153
      friendly_name: Ridge
      max_mireds: 500
      min_mireds: 153
      state: 'on'
      supported_features: 43
    light.living_room_turtle_chair:
      brightness: 255
      color_temp: 153
      friendly_name: Turtle chair
      max_mireds: 500
      min_mireds: 153
      state: 'on'
      supported_features: 43
    light.living_room_tv:
      brightness: 255
      color:
        x: 0.323
        y: 0.329
      friendly_name: TV
      hs_color:
      - 0
      - 0.392
      rgb_color:
      - 255
      - 254
      - 254
      state: 'on'
      supported_features: 57
      update_available: true
      xy_color:
      - 0.324
      - 0.329
- id: '1579734722178'
  name: Room Rein Evening
  entities:
    light.room_rein_1:
      brightness: 1
      friendly_name: Rein 1
      state: 'on'
      supported_features: 41
    light.room_rein_2:
      brightness: 1
      friendly_name: Rein 2
      state: 'on'
      supported_features: 41
    light.room_rein_bed:
      brightness: 1
      friendly_name: Rein bed
      state: 'on'
      supported_features: 41
- id: '1579734766317'
  name: Room Rein Bright
  entities:
    light.room_rein_1:
      brightness: 254
      friendly_name: Rein 1
      state: 'on'
      supported_features: 41
    light.room_rein_2:
      brightness: 253
      friendly_name: Rein 2
      state: 'on'
      supported_features: 41
    light.room_rein_bed:
      brightness: 253
      friendly_name: Rein bed
      state: 'on'
      supported_features: 41
