play_sound:
  alias: Play a sound effect
  sequence:
  - service: media_player.volume_set
    data_template:
      entity_id: '{{ media_id }}'
    data:
      volume_level: 0.4
  - service: media_player.play_media
    data_template:
      entity_id: '{{ media_id }}'
      media_content_id: '{{ sound_file }}'
      media_content_type: music
brightness_up:
  alias: Brightness up
  sequence:
  - service: light.turn_on
    data_template:
      entity_id: light.living_room
      transition: 1
      brightness: >
        {% set n = states.input_number.brightness_living_room.state | int + 100 %}
        {% if n > 255 %}
        255
        {% else %}
        {{ n }}
        {% endif %}
  - service: input_number.set_value
    data_template:
      entity_id: input_number.brightness_living_room
      value: >
        {% set n = states.input_number.brightness_living_room.state | int + 100 %}
        {% if n > 255 %}
        255
        {% else %}
        {{ n }}
        {% endif %}
brightness_down:
  alias: Brightness down
  sequence:
  - service: light.turn_on
    data_template:
      entity_id: light.living_room
      transition: 1
      brightness: >
        {% set n = states.input_number.brightness_living_room.state | int - 100 %}
        {% if n <= 1 %}
        1
        {% else %}
        {{ n }}
        {% endif %}
  - service: input_number.set_value
    data_template:
      entity_id: input_number.brightness_living_room
      value: >
        {% set n = states.input_number.brightness_living_room.state | int - 100 %}
        {% if n <= 1 %}
        1
        {% else %}
        {{ n }}
        {% endif %}
set_brightness:
  alias: Set brightness
  sequence:
  - service: light.turn_on
    data_template:
      entity_id: '{{ entity_id }}'
      transition: 1
      brightness: >
        {% set n = brightness|float %}
        {% if n == 0 %}
        0
        {% else %}
        {% if min_brightness is defined %}
        {% set min = min_brightness %}
        {% else %}
        {% set min = 1 %}
        {% endif %}
        {% if max_brightness is defined %}
        {% set max = max_brightness %}
        {% else %}
        {% set max = 255 %}
        {% endif %}
        {% set t = (((n/255)*(255 - min - (255 - max))) + min)|int %}
        {{ t }}
        {% endif %}
light_hallway_high:
  alias: Light Hallway high
  sequence:
  - service: light.turn_on
    entity_id: light.hallway
    data:
      brightness: 100
light_hallway_low:
  alias: Light Hallway low
  sequence:
  - service: light.turn_on
    entity_id: light.hallway
    data:
      brightness: 1
light_hallway_night:
  alias: Light Hallway night
  sequence:
  - service: light.turn_off
    entity_id: light.hallway_front
  - service: light.turn_on
    entity_id: light.hallway_back
    data:
      brightness: 1
ventilation_set_speed:
  alias: Ventilation set speed
  sequence:
  - service: script.toggle
    data_template:
      entity_id: 'script.ventilation_{{ speed }}'
ventilation_off:
  alias: Ventilation off
  sequence:
  - service: switch.turn_off
    entity_id: switch.ventilation_medium
  - service: switch.turn_off
    entity_id: switch.ventilation_high
ventilation_medium:
  alias: Ventilation low
  sequence:
  - service: switch.turn_off
    entity_id: switch.ventilation_high
  - service: switch.turn_on
    entity_id: switch.ventilation_medium
ventilation_high:
  alias: Ventilation high
  sequence:
  - service: switch.turn_off
    entity_id: switch.ventilation_medium
  - service: switch.turn_on
    entity_id: switch.ventilation_high
away_mode_on:
  alias: Away mode on
  sequence:
  - service: climate.set_preset_mode
    entity_id: climate.heating
    data:
      preset_mode: away
away_mode_off:
  alias: Away mode off
  sequence:
  - service: climate.set_preset_mode
    entity_id: climate.heating
    data:
      preset_mode: none
guest_mode_on:
  alias: Guest mode on
  sequence:
  - service: script.turn_on
    entity_id: script.check_guest_mode_timer
guest_mode_off:
  alias: Guest mode off
  sequence:
  - delay:
      seconds: 1
check_guest_mode_timer:
  alias: Check Guest mode timer
  sequence:
  - condition: template
    value_template: "{{ as_timestamp(now()) > as_timestamp(states('input_datetime.guest_mode_active_until')) }}"
  - service: script.reset_guest_mode_timer
reset_guest_mode_timer:
  alias: Reset Guest mode timer
  sequence:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.guest_mode_active_until
    data_template:
      datetime: "{{ (as_timestamp(now()) + 12 * 3600) | timestamp_custom('%Y-%m-%d %H:%M:00') }}"
restart_light_hallway_timer:
  alias: Restart light Hallway timer
  sequence:
  - service: timer.cancel
    entity_id: timer.light_hallway
  - service: timer.start
    entity_id: timer.light_hallway
restart_light_storage_room_timer:
  alias: Restart light Storage Room timer
  sequence:
  - service: timer.cancel
    entity_id: timer.light_storage_room
  - service: timer.start
    entity_id: timer.light_storage_room
restart_light_toilet_timer:
  alias: Restart light Toilet timer
  sequence:
  - service: timer.cancel
    entity_id: timer.light_toilet
  - service: timer.start
    entity_id: timer.light_toilet
turn_on_light_hallway:
  alias: Turn on light Hallway
  sequence:
  - service: script.turn_on
    data_template:
      entity_id: >
        {% if states('binary_sensor.sleep_mode') == 'on' %}
        script.light_hallway_night
        {% elif states('sun.sun') == 'below_horizon' %}
        script.light_hallway_low
        {% else %}
        script.light_hallway_high
        {% endif %}
turn_off_living_room:
  alias: Turn off Living Room
  sequence:
  - service: script.turn_on
    entity_id: script.turn_on_light_hallway
  - service: script.turn_on
    entity_id: script.restart_light_hallway_timer
  - service: light.turn_off
    entity_id: light.living_room
  - service: light.turn_off
    entity_id: light.kitchen
  - service: media_player.turn_off
    entity_id: media_player.tv
  # - service: media_player.turn_off
  #   entity_id: media_player.google_home
  - service: media_player.volume_set
    data:
      entity_id: media_player.googlehome2198
      volume_level: 0.8
  - service: media_player.play_media
    data:
      entity_id: media_player.googlehome2198
      media_content_type: music
      media_content_id: !secret sfx_url_logoff
washing_machine_done_notification:
  alias: Washing machine done notification
  sequence:
  - service: notify.mobile_app_iphone_rein
    data:
      message: 'Washing machine is done 👚👕'
  - service: notify.mobile_app_iphone_van_bas
    data:
      message: 'Washing machine is done 👚👕'
  - service: notify.tv
    data:
      message: 'Washing machine is done'
