---
filter:
  include_entities:
    - input_boolean.guest_mode
    - light.living_room_ridge
    - light.living_room_turtle_chair
    - light.tv
    - light.couch
    - light.corner
    - light.kitchen_map
    - light.christmas_tree
    - light.rein_ceiling
    - light.room_rein_bed
    - light.bas_ceiling
    - light.room_bas_bed
    - light.hallway
    - scene.living_room_evening
    - scene.living_room_shawarma
    - scene.room_rein_evening
    - scene.room_rein_bright
    - climate.heating
    - fan.ventilation
