---
# push:
#   categories:
#     - name: Alarm
#       identifier: 'alarm'
#       actions:
#         - identifier: 'SOUND_ALARM'
#           title: 'Sound Alarm'
#           activationMode: 'background'
#           authenticationRequired: true
#           destructive: true
#           behavior: 'default'
#         - identifier: 'SILENCE_ALARM'
#           title: 'Silence Alarm'
#           activationMode: 'background'
#           authenticationRequired: true
#           destructive: false
#           behavior: 'textInput'
#           textInputButtonTitle: 'Silencio!'
#           textInputPlaceholder: 'Placeholder'
