---
- host: !secret lg_tv_ip_address
  name: TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret lg_tv_mac_address
  customize:
    sources:
      - HDMI1
      - HDMI2
      - HDMI3
      - HDMI4
      - Spotify Music - Luister gratis op LG TV
      - YouTube
      - Netflix
      - Videoland
      - Disney+
      - NPO
      - Kijk
      - RTL XL
      - Radio [Dutch]
      - Pathé Thuis
      - Webbrowser
