---
- platform: template
  sensors:
    washing_machine:
      friendly_name: Washing machine
      value_template: >
        {{ states('sensor.washing_machine_usage') | float(0) > 3 }}
      delay_on: '00:01:00'
      delay_off: '00:04:00'
    tv_source_youtube:
      friendly_name: TV source YouTube
      value_template: >
        {{
          states('media_player.tv') == 'on' and
          (
            state_attr('media_player.tv', 'source') == 'YouTube' or
            (
              state_attr('media_player.tv', 'source') == 'HDMI3' and
              state_attr('media_player.chromecast', 'app_name') == 'YouTube'
            )
          )
        }}
    tv_source_spotify:
      friendly_name: TV source Spotify
      value_template: >
        {{
          states('media_player.tv') == 'on' and
          (
            state_attr('media_player.tv', 'source') == 'Spotify Music - Luister gratis op LG TV' or
            (
              state_attr('media_player.tv', 'source') == 'HDMI3' and
              state_attr('media_player.chromecast', 'app_name') == 'Spotify'
            )
          )
        }}
    tv_source_netflix:
      friendly_name: TV source Netflix
      value_template: >
        {{
          states('media_player.tv') == 'on' and
          (
            state_attr('media_player.tv', 'source') == 'Netflix' or
            (
              state_attr('media_player.tv', 'source') == 'HDMI3' and
              state_attr('media_player.chromecast', 'app_name') == 'Netflix'
            )
          )
        }}
    tv_source_plex:
      friendly_name: TV source Plex
      value_template: >
        {{
          states('media_player.tv') == 'on' and
          (
            state_attr('media_player.tv', 'source') == 'Plex' or
            (
              state_attr('media_player.tv', 'source') == 'HDMI3' and
              state_attr('media_player.chromecast', 'app_name') == 'Plex'
            )
          )
        }}
    tv_source_tunein:
      friendly_name: TV source TuneIn
      value_template: >
        {{
          states('media_player.tv') == 'on' and
          (
            state_attr('media_player.tv', 'source') == 'HDMI3' and
            state_attr('media_player.chromecast', 'app_name') == 'TuneIn Free'
          )
        }}
    tv_source_off:
      friendly_name: TV source off
      value_template: >
        {{
          states('binary_sensor.tv_source_youtube') == 'off' and
          states('binary_sensor.tv_source_spotify') == 'off' and
          states('binary_sensor.tv_source_netflix') == 'off' and
          states('binary_sensor.tv_source_plex') == 'off' and
          states('binary_sensor.tv_source_tunein') == 'off'
        }}
    ventilation_usage_low:
      friendly_name: Ventilation usage low
      delay_on: '00:01:00'
      delay_off: '00:01:00'
      value_template: "{{ states('sensor.ventilation_usage')|int < 6 }}"
    ventilation_usage_medium:
      friendly_name: Ventilation usage medium
      delay_on: '00:01:00'
      delay_off: '00:01:00'
      value_template: >
        {{
          states('sensor.ventilation_usage')|int >= 6 and
          states('sensor.ventilation_usage')|int < 15
        }}
    ventilation_usage_high:
      friendly_name: Ventilation usage high
      delay_on: '00:01:00'
      delay_off: '00:01:00'
      value_template: "{{ states('sensor.ventilation_usage')|int >= 15 }}"
    motion_hallway:
      friendly_name: Motion hallway
      value_template: >
        {{
          states('binary_sensor.motion_hallway_front') == 'on' or
          states('binary_sensor.motion_hallway_back') == 'on'
        }}
    nobody_home:
      friendly_name: Nobody home
      delay_on: '00:15:00'
      value_template: >
        {{
          states('person.bas_menting') != 'home' and
          states('person.rein_van_haaren') != 'home' and
          states('person.renske_van_der_zalm') != 'home'
        }}
    sleep_mode:
      friendly_name: Sleep mode
      delay_on: '00:01:00'
      value_template: >
        {{
          states('sun.sun') == 'below_horizon' and
          states('binary_sensor.nobody_home') != 'on' and
          states('media_player.tv') == 'off' and
          states('light.living_room') == 'off' and
          states('light.room_rein') == 'off' and
          states('light.room_bas') == 'off'
        }}
    ventilation_shower:
      friendly_name: Ventilation shower
      delay_on: '00:02:00'
      delay_off: '00:20:00'
      value_template: >
        {{ states('sensor.environment_bathroom_humidity') | int >= 73 }}
    ventilation_toilet_high:
      friendly_name: Ventilation toilet high
      delay_off: '00:05:00'
      value_template: >
        {{
          states('input_boolean.ventilation_high_when_leaving_toilet') == 'on' and
          states('light.toilet') == 'off'
        }}
    ventilation_toilet_medium:
      friendly_name: Ventilation toilet medium
      delay_off: '00:05:00'
      value_template: >
        {{ states('light.toilet') == 'on' }}
    ventilation_high:
      friendly_name: Ventilation high
      value_template: >
        {{
          states('binary_sensor.ventilation_shower') == 'on' or
          states('binary_sensor.ventilation_toilet_high') == 'on'
        }}
    ventilation_medium:
      friendly_name: Ventilation medium
      value_template: >
        {{
          states('binary_sensor.ventilation_high') != 'on' and
          states('binary_sensor.ventilation_toilet_medium') == 'on'
        }}
    ventilation_off:
      friendly_name: Ventilation low
      delay_on: '00:00:01'
      value_template: >
        {{
          states('binary_sensor.ventilation_high') != 'on' and
          states('binary_sensor.ventilation_medium') != 'on'
        }}
    light_toilet_5_minutes_on:
      friendly_name: Light toilet 5 minutes on
      delay_on: '00:05:00'
      value_template: >
        {{ states('light.toilet') == 'on' }}
