---
 - platform: generic_thermostat
   name: Heating
   heater: switch.heater
   target_sensor: sensor.temperature
   min_temp: 13
   max_temp: 26
   ac_mode: false
   target_temp: 20
   cold_tolerance: 0.3
   hot_tolerance: 0
   min_cycle_duration:
     seconds: 30
   keep_alive:
     minutes: 3
   initial_hvac_mode: 'heat'
   away_temp: 17
   precision: 0.5
