---
- platform: template
  fans:
    ventilation:
      friendly_name: 'Ventilation'
      value_template: >
        {% if states.sensor.ventilation_usage.state|int >= 6 %}
        on
        {% else %}
        off
        {% endif %}
      speed_template: >
        {% if states.sensor.ventilation_usage.state|int >= 15 %}
        high
        {% elif states.sensor.ventilation_usage.state|int >= 6 %}
        medium
        {% else %}
        low
        {% endif %}
      turn_on:
        service: input_boolean.toggle
        entity_id: input_boolean.dummy
      turn_off:
        service: script.toggle
        entity_id: script.ventilation_off
      set_speed:
        service: script.ventilation_set_speed
        data_template:
          speed: '{{ speed }}'
