---
guest_mode:
  name: Guest mode
  icon: mdi:bag-checked
  initial: off
enable_washing_machine_schedule:
  name: Enable washing machine schedule
  icon: mdi:clock-check
  initial: off
dummy:
  name: Dummy input boolean
  initial: off
ventilation_high_when_leaving_toilet:
  name: Ventilation high when leaving toilet
  initial: off
ventilation_high_when_toilet_light_on:
  name: Ventilation high when toilet light on
  initial: off
test_boolean:
  name: Test Boolean
  initial: off
