---
end_time_washing_machine:
  name: End time washing machine
  has_date: true
  has_time: true
  icon: mdi:clock-digital
guest_mode_active_until:
  name: Guest mode active until
  has_date: true
  has_time: true
  icon: mdi:account-clock
