---
- platform: mqtt
  schema: json
  name: Couch
  command_topic: 'zigbee2mqtt/living_room_couch/set'
  state_topic: 'zigbee2mqtt/living_room_couch'
  color_temp: false
  brightness: true
  rgb: false

- platform: mqtt
  schema: json
  name: Hallway
  command_topic: 'zigbee2mqtt/hallway/set'
  state_topic: 'zigbee2mqtt/hallway'
  color_temp: false
  brightness: true
  rgb: false

- platform: mqtt
  schema: json
  name: Hallway Front
  command_topic: 'zigbee2mqtt/hallway_front/set'
  state_topic: 'zigbee2mqtt/hallway_front'
  color_temp: false
  brightness: true
  rgb: false

- platform: mqtt
  schema: json
  name: Hallway Back
  command_topic: 'zigbee2mqtt/hallway_back/set'
  state_topic: 'zigbee2mqtt/hallway_back'
  color_temp: false
  brightness: true
  rgb: false

- platform: mqtt
  schema: json
  name: Room Rein ceiling
  command_topic: 'zigbee2mqtt/room_rein_ceiling/set'
  state_topic: 'zigbee2mqtt/room_rein_ceiling'
  color_temp: false
  brightness: true
  rgb: false

- platform: mqtt
  schema: json
  name: Room Bas ceiling
  command_topic: 'zigbee2mqtt/room_bas_ceiling/set'
  state_topic: 'zigbee2mqtt/room_bas_ceiling'
  color_temp: true
  brightness: true
  rgb: false

- platform: mqtt
  name: Toilet
  command_topic: "home/sonoff_mini_toilet/cmnd/POWER"
  state_topic: "home/sonoff_mini_toilet/tele/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "home/sonoff_mini_toilet/tele/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1

- platform: switch
  name: Christmas tree
  entity_id: switch.living_room_christmas_tree

- platform: group
  name: All
  entities:
    - light.living_room_ridge
    - light.living_room_turtle_chair
    - light.living_room_tv
    - light.couch
    - light.corner
    - light.kitchen_map
    - light.hallway
    - light.room_rein
    - light.room_bas
    - light.christmas_tree

- platform: group
  name: Living room
  entities:
    - light.couch
    - light.living_room_ridge
    - light.living_room_turtle_chair
    - light.corner
    - light.christmas_tree

- platform: group
  name: Kitchen
  entities:
    - light.kitchen_cabinets_map
    - light.kitchen_extractor_hood

- platform: group
  name: Living Room and Kitchen cabinets
  entities:
    - light.living_room
    - light.kitchen_cabinets_map

- platform: group
  name: Room Rein
  entities:
    - light.room_rein_1
    - light.room_rein_2
    - light.room_rein_bed

- platform: group
  name: Room Bas
  entities:
    - light.room_bas_ceiling
    - light.room_bas_bed

- platform: template
  lights:
    # tv:
    #   friendly_name: 'TV'
    #   level_template: >
    #     {% set n = states.light.living_room_tv.attributes.brightness|int %}
    #     {% if n == 0 %}
    #     0
    #     {% else %}
    #     {% set b = ((n-29)/(255 - 29 - (255 - 255)))*255 %}
    #     {% if b < 1 %}
    #     0
    #     {% else %}
    #     {{ b|int }}
    #     {% endif %}
    #     {% endif %}
    #   value_template: '{{ states.light.living_room_tv.attributes.brightness|int > 26 }}'
    #   turn_on:
    #     service: light.turn_on
    #     data:
    #       entity_id: light.living_room_tv
    #   turn_off:
    #     service: light.turn_off
    #     data:
    #       entity_id: light.living_room_tv
    #   set_level:
    #     service: script.set_brightness
    #     data_template:
    #       entity_id: light.living_room_tv
    #       brightness: '{{ brightness }}'
    #       min_brightness: 29
    corner:
      friendly_name: 'Corner'
      level_template: >
        {% set n = states.light.living_room_corner.attributes.brightness|int %}
        {% if n == 0 %}
        0
        {% else %}
        {% set b = ((n-29)/(255 - 29 - (255 - 255)))*255 %}
        {% if b < 1 %}
        0
        {% else %}
        {{ b|int }}
        {% endif %}
        {% endif %}
      value_template: '{{ states.light.living_room_corner.attributes.brightness|int > 26 }}'
      turn_on:
        service: light.turn_on
        entity_id: light.living_room_corner
      turn_off:
        service: light.turn_off
        entity_id: light.living_room_corner
      set_level:
        service: script.set_brightness
        data_template:
          entity_id: light.living_room_corner
          brightness: '{{ brightness }}'
          min_brightness: 29
    kitchen_cabinets_map:
      friendly_name: 'Kitchen cabinets'
      level_template: >
        {% set n = states.light.kitchen_cabinets.attributes.brightness|int %}
        {% if n == 0 %}
        0
        {% else %}
        {% set b = ((n-0)/(255 - 0 - (255 - 240)))*255 %}
        {% if b < 1 %}
        0
        {% else %}
        {{ b|int }}
        {% endif %}
        {% endif %}
      value_template: "{{ states('light.kitchen_cabinets') }}"
      turn_on:
        service: light.turn_on
        entity_id: light.kitchen_cabinets
      turn_off:
        service: light.turn_off
        entity_id: light.kitchen_cabinets
      set_level:
        service: script.set_brightness
        data_template:
          entity_id: light.kitchen_cabinets
          brightness: '{{ brightness }}'
          max_brightness: 240
