---
# - platform: template
#   switches:
#     washing_mashine_toggler:
#       friendly_name: Washing Machine power
#       value_template: "{{ is_state('switch.washing_machine','on')}}"
#       turn_on:
#         service: switch.turn_on
#         data:
#           entity_id: switch.washing_machine
#       turn_off:
#         service: switch.turn_off
#         data_template:
#           entity_id: >
#             {% if is_state('binary_sensor.washing_machine', 'off') %}
#               switch.washing_machine
#             {% else %}
#               switch.null
#             {% endif %}

 - platform: template
   switches:
     heating_away_mode:
       friendly_name: Heating in away mode
       value_template: "{{ is_state_attr('climate.heating', 'preset_mode', 'away') }}"
       turn_on:
         service: climate.set_preset_mode
         data:
           entity_id: climate.heating
           preset_mode: away
       turn_off:
         service: climate.set_preset_mode
         data:
           entity_id: climate.heating
           preset_mode: none

 - platform: mqtt
   name: heater
   command_topic: 'home/heater/set'
