---
- platform: template
  switches:
    heating_away_mode:
      friendly_name: Heating in away mode
      value_template: "{{ is_state_attr('climate.heating', 'preset_mode', 'away') }}"
      turn_on:
        service: climate.set_preset_mode
        data:
          entity_id: climate.heating
          preset_mode: away
      turn_off:
        service: climate.set_preset_mode
        data:
          entity_id: climate.heating
          preset_mode: none

- platform: template
  switches:
    button_ventilation_off:
      friendly_name: Ventilation off
      value_template: "{{ is_state('switch.ventilation_medium', 'off') and is_state('switch.ventilation_high', 'off') }}"
      turn_on:
        service: script.toggle
        data:
          entity_id: script.ventilation_off
      turn_off:
        service: script.toggle
        data:
          entity_id: script.ventilation_off
    button_ventilation_medium:
      friendly_name: Ventilation medium
      value_template: "{{ is_state('switch.ventilation_medium', 'on') }}"
      turn_on:
        service: script.toggle
        data:
          entity_id: script.ventilation_medium
      turn_off:
        service: script.toggle
        data:
          entity_id: script.ventilation_medium
    button_ventilation_high:
      friendly_name: Ventilation high
      value_template: "{{ is_state('switch.ventilation_high', 'on') }}"
      turn_on:
        service: script.toggle
        data:
          entity_id: script.ventilation_high
      turn_off:
        service: script.toggle
        data:
          entity_id: script.ventilation_high

- platform: mqtt
  name: Heater
  command_topic: 'home/esp1_attic/cmd'
  state_topic: 'home/esp1_attic/relay_1/state'
  availability_topic: 'home/esp1_attic/state'
  payload_on: 'GPIO,12,0'
  payload_off: 'GPIO,12,1'
  state_on: '0'
  state_off: '1'

- platform: mqtt
  name: Ventilation medium
  command_topic: 'home/esp1_attic/cmd'
  state_topic: 'home/esp1_attic/relay_2/state'
  availability_topic: 'home/esp1_attic/state'
  payload_on: 'GPIO,14,0'
  payload_off: 'GPIO,14,1'
  state_on: '0'
  state_off: '1'

- platform: mqtt
  name: Ventilation high
  command_topic: 'home/esp1_attic/cmd'
  state_topic: 'home/esp1_attic/relay_3/state'
  availability_topic: 'home/esp1_attic/state'
  payload_on: 'GPIO,13,0'
  payload_off: 'GPIO,13,1'
  state_on: '0'
  state_off: '1'

- platform: mqtt
  name: Start washing machine
  command_topic: 'home/esp2_bathroom/cmd'
  state_topic: 'home/esp2_bathroom/relay_1/state'
  availability_topic: 'home/esp1_bathroom/state'
  payload_on: 'Pulse,14,0,500'
  payload_off: 'GPIO,14,1'
  state_on: '0'
  state_off: '1'
