---
- name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 75
  icon: mdi:home

- name: Work
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 200
  icon: mdi:work

- name: Renske
  latitude: !secret latitude_renske
  longitude: !secret longitude_renske
  radius: 100
  icon: mdi:face-woman
