---
- alias: 'Away mode: Turn on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.nobody_home
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.away_mode_on
    - service: notify.mobile_app_iphone_rein
      data:
        message: 'Away mode is set to: on'
- alias: 'Away mode: Turn off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.nobody_home
      to: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.away_mode_off
    - service: notify.mobile_app_iphone_rein
      data:
        message: 'Away mode is set to: off'
