---
- alias: 'Away mode: Turn on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.nobody_home
      to: 'on'
    - platform: state
      entity_id: input_boolean.guest_mode
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.away_mode_on
- alias: 'Away mode: Turn off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.nobody_home
      to: 'off'
    - platform: state
      entity_id: input_boolean.guest_mode
      to: 'off'
  action:
    - service: script.turn_on
      entity_id: script.away_mode_off
