---
- alias: 'Button: Hallway front: on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.button_hallway_front
      to: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.hallway
        brightness: >
          {% if states('sun.sun') == 'below_horizon' %}
          1
          {% else %}
          100
          {% endif %}
    - service: script.turn_on
      entity_id: script.restart_light_hallway_timer
- alias: 'Button: Hallway front: off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.button_hallway_front
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.hallway
