---
- alias: 'Google Home Mini: Volume 50% on startup'
  initial_state: 'on'
  trigger:
    - entity_id: media_player.google_home
      platform: state
      from: 'off'
  action:
    - service: media_player.volume_set
      entity_id: media_player.google_home
      data:
        volume_level: 0.4
