---
- alias: 'Home Assistant: On start'
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  action:
    - service: script.turn_on
      entity_id: script.restart_light_hallway_timer
    - service: script.turn_on
      entity_id: script.restart_light_storage_room_timer
    - service: script.turn_on
      entity_id: script.ventilation_off
