---
- alias: 'Light kitchen: Turn off light extractor hood'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: light.living_room_and_kitchen_cabinets
      to: 'off'
  action:
    - service: light.turn_off
      entity_id: light.kitchen_extractor_hood
