---
- alias: 'Light Hallway: Reset and start timer'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway
      to: 'off'
    - platform: state
      entity_id: binary_sensor.door_living_room
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.restart_light_hallway_timer
- alias: 'Light Hallway: Turn on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_living_room
      to: 'on'
  condition:
    - condition: state
      entity_id: light.hallway
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.turn_on_light_hallway
- alias: 'Light Hallway: Turn off'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.light_hallway
  condition:
    - condition: state
      entity_id: binary_sensor.motion_hallway
      state:  'off'
  action:
    - service: light.turn_off
      entity_id: light.hallway
