---
- alias: 'Light Hallway: Start timer and turn light on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway
      to: 'off'
    - platform: state
      entity_id: binary_sensor.door_living_room
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.light_hallway
    - service: timer.start
      entity_id: timer.light_hallway
- alias: 'Light Hallway: Turn on'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_living_room
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.hallway
- alias: 'Light Hallway: Turn off'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.light_hallway
  condition:
    - condition: state
      entity_id: binary_sensor.motion_hallway
      state:  'off'
  action:
    - service: light.turn_off
      entity_id: light.hallway
