---
- alias: 'Light TV: Spotify'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.tv_source_spotify
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.living_room_tv
      data:
        rgb_color: [0, 255, 0]
        transition: 2
- alias: 'Light TV: TuneIn'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.tv_source_tunein
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.living_room_tv
      data:
        rgb_color: [0, 255, 0]
        transition: 2
- alias: 'Light TV: YouTube'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.tv_source_youtube
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.living_room_tv
      data:
        rgb_color: [255, 0, 0]
        transition: 2
- alias: 'Light TV: Netflix'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.tv_source_netflix
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.living_room_tv
      data:
        rgb_color: [255, 0, 0]
        transition: 2
- alias: 'Light TV: Off'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.tv_source_off
      to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.living_room_tv
      data:
        rgb_color: [175, 0, 255]
        transition: 2
