---
- alias: 'Utilities: Chromecast off when TV off'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: media_player.tv
    to: 'off'
  action:
    - service: media_player.turn_off
      data:
        entity_id: media_player.chromecast
