---
- alias: 'Ventilation: Speed off'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.ventilation_usage
    below: 5
  action:
    - service: script.toggle
      entity_id: script.ventilation_off
- alias: 'Ventilation: Speed medium'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.ventilation_usage
    above: 5
    below: 10
  action:
    - service: script.toggle
      entity_id: script.ventilation_medium
- alias: 'Ventilation: Speed high'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.ventilation_usage
    above: 10
  action:
    - service: script.toggle
      entity_id: script.ventilation_high